### PR TITLE
Added DynamicData

### PR DESCRIPTION
**Pull request by RLittlesII**
Basic DynamicData implementation

- Still needs disposal logic wired up
- Not using all the power of Reactive Extensions
- Might be more complexity than your app is ready to sustain

### CODE REVIEW

**Comment by SkyeHoefling** [comment]
Thank you for submitting this PR. I am going to download the code and run it through the Xamarin Profiler.

This morning I was looking at the implementation of the `ConcurrentStack` which is thread-safe data structure I used to solve this problem. What is DynamicData using to handle thread-safety? Is it using locks or is it using something like a CAS (Compare And Swap) that doesn't require locks but is still thread safe

**Comment by SkyeHoefling** [comment]
After running this through my tests, this does not solve the memory leak. Using the Android Emulator on my Surface Book 2 the entire app becomes unresponsive the 2nd time through populating the ListView. At this point I am not even able to open the modal window or clear the list, I can only close the app and start over.

image

I believe there may be a memory leak caused in how DynamicData adds items to the binded ObservableCollection

**Comment by RLittlesII** [comment]
Hmm.  Then it wouldn't be the ObservableCollection causing the leak.  I didn't test this on Android.  Only iOS.  Let me look into this a bit further and try and understand.  I also didn't go all-in on the Rx as I know that is a big deviation from where you are currently.

Is it a memory leak or a thread crashing?

**Comment by SkyeHoefling** [comment]
Thanks for all the effort on this, I really can't tell you how much I appreciate this.

> Is it a memory leak or a thread crashing?

I'm not sure how to tell the difference. When I hook this up the Xamarin Profiler it creates the same objects in high volume as the initial sample. This tells me it is leaking memory as it is unable to destroy the System.Delegate object and as the app runs the values climb significantly from this.

The below tests follow the exact same testing pattern. I have attached the Xamarin Profiler to each test as a fresh start to ensure the memory has been cleaned up from the previous test. All results below are done using the Android Emulator from a Surface Book 2 with the app built in Debug mode

1. Open App
2. Tap start button to begin stress test
3. Once 5000 items are loaded tap the clear button to reset the collections
4. Tap start button to begin stress test

Expected Result: Both tests should continue until completion

## Quick Overview
| Test                    | Results                           | Time       | Allocated Memory | Test Finished                                   |
|-------------------|---------------------------|-----------|---------------------|---------------------------------------|
| Baseline              | ❌ Memory Leaked      |  20m 34s | 1.1 GB                   | ❌ UI became unresponsive 7,500 |
| DynamicData      | ❌ Memory Leaked      | 18m 1s    | 1015.9 MB            | ❌ UI became unresponsive  7,500 |
| ConcurrentStack | ✔ No Memory Leaked | 6m 36s   | 348.9 MB              | ✔ Test finished 10,000                    |  

## Baseline Test
❌ Failure

The baseline test or memory leak test adds items to an `ObservableCollection<string>` via the event. As it adds each item the Garbage Collector doesn't understand how to properly delete the `System.Delelgate[]` from memory. This is because the `ObservableCollection` grabs a reference to it that it won't release. As far as I understand what is happening is when the object is added to the collection from the event which is scoped at a background thread the collection that is not thread safe then grabs a reference to the scope of where the object was created. This is what causes the memory leak.

**Findings**
- Allocated Memory: 1.1 GB
- Largest Object: `System.Delegate[]` @ 902.8 MB
- Unable to complete test, UI locked up at around 7500 items added

### Screenshot
image


## DynamicData Test
❌ Failure

The DynamicData implementation binds the sources to a `ReadOnlyObservableCollection<string>`, as far as I can tell it is still holding onto the references of `System.Delegate[]` which is causing the memory leak in the baseline test. I believe this is caused by the event which binds to the data in the same thread. Since the event is triggered from a different thread it causes some type of reference conflict which holds on to the scope of the `System.Delegate` which means it never gets deleted by the GC. 

**Findings**
- Allocated Memory: 1015.9 MB
- Largest Object: `System.Delegate[]` @ 828.1 MB
- Unable to complete test, UI locked up at 7500 items added

### Screenshot
image

## ConcurrentStack Test
✔ Success

The `ConcurrentStack` implementation uses the thread safe collection and on every push to the collection it reloads a new instance of `ObservableCollection<string>` which is then streamed to the UI. In all tests this is the safest implementation as the GC properly deletes events and the `ObservableCollection<string>` doesn't create any strong references to the `System.Delegate`.

**Findings**
- Allocated Memory: 348.9 MB
- Largest Object: `System.String[]` @ 285.6MB
- The only implementation that was able to complete the test loading 10,000 items

### Screenshot
image

**Comment by RLittlesII** [comment]
@ahoefling Let me digest this a bit more.

To answer you're questions.  DynamicData does use a [Synchronize](https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh229583(v=vs.103)) method for locking safety.  This doesn't sound like a list issue, this sounds more like a delegate release issue.

I am going to play around with this a bit more this week.  Now it is less about solving your problem and more about proving where the problem emanates from!

Feel free to reject the PR.

With Rx there are thread marshaling techniques that can be used to keep the UI thread from locking.  Now I want to see if that's the problem!

**Comment by SkyeHoefling** [comment]
@RLittlesII 
> this sounds more like a delegate release issue.

I 100% agree with you and from my testing it appears that when we use a thread-safe collection from the concurrent collections library the problem resolves itself. If we use a non-thread safe collection it doesn't release the delegate. I think having an Rx solution like this is very valuable in this code sample and I am going to merge this as is.

## Next Steps
- I am going to move documentation of my test results to a readme file
- If you figure out the problem please submit a follow-up PR
- I am going to start work on making a new ConcurrentObservableCollection - not sure if it will get anywhere but if it does could be very useful to the ecosystem
- If there is any problem with DynamicData I am more than happy to help you out with determining an appropriate solution

**Pull request merged**
